version: "3.0"
services: 
  db:
    image: mysql:8
    container_name: Stock_Mysql_DB
    environment: 
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_USER: stock
      MYSQL_PASSWORD: stockpw
      MYSQL_DATABASE: castock
    ports: 
      - 3307:3306
    command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    volumes:
          - /Users/Shared/data/mysql-test:/var/lib/mysql
    restart: always
  app:
    build: .
    container_name: castock_spring
    image: openjdk:11
    ports: 
      - "11111:8080"
    volumes:
      - ./app:/app
    working_dir: /app
    depends_on:
        - db
    restart: always